apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helios-ceo
  namespace: default
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
    run.googleapis.com/startup-cpu-boost: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/timeout: "900s"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      containers:
      - image: gcr.io/helios-pod-system/helios-ceo:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "helios-pod-system"
        - name: GOOGLE_CLOUD_REGION
          value: "us-central1"
        - name: ENABLE_PARALLEL_PROCESSING
          value: "true"
        - name: ENABLE_BATCH_CREATION
          value: "true"
        - name: MIN_OPPORTUNITY_SCORE
          value: "7.0"
        - name: MIN_AUDIENCE_CONFIDENCE
          value: "7.0"
        - name: MAX_EXECUTION_TIME
          value: "900"
        - name: PRINTIFY_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: helios-secrets
              key: printify-api-token
        - name: PRINTIFY_SHOP_ID
          value: "8542090"
        - name: GOOGLE_MCP_URL
          value: "http://helios-mcp:8787"
        - name: GOOGLE_MCP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: helios-secrets
              key: google-mcp-auth-token
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      serviceAccountName: helios-automation-sa
