steps:
  # Deploy Helios AI Orchestrator service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'helios-orchestrator', 
           '--source', './deployment/run/orchestrator',
           '--region', 'us-central1', 
           '--platform', 'managed', 
           '--allow-unauthenticated', 
           '--service-account', 'helios-vertex-ai@$PROJECT_ID.iam.gserviceaccount.com',
           '--set-env-vars', 'SERVICE_TYPE=orchestrator,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,DRY_RUN=false,ALLOW_LIVE_PUBLISHING=true',
           '--set-secrets', 'PRINTIFY_API_TOKEN=printify-api-token:latest,PRINTIFY_SHOP_ID=printify-shop-id:latest,GOOGLE_API_KEY=google-api-key:latest',
           '--port', '8080',
           '--memory', '1Gi',
           '--cpu', '1',
           '--max-instances', '10',
           '--min-instances', '0']

  # Deploy Helios AI Agents service to Cloud Run  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'helios-ai-agents',
           '--source', './deployment/run/agents',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated',
           '--service-account', 'helios-vertex-ai@$PROJECT_ID.iam.gserviceaccount.com',
           '--set-env-vars', 'SERVICE_TYPE=ai_agents,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,DRY_RUN=false,ALLOW_LIVE_PUBLISHING=true',
           '--set-secrets', 'PRINTIFY_API_TOKEN=printify-api-token:latest,PRINTIFY_SHOP_ID=printify-shop-id:latest,GOOGLE_API_KEY=google-api-key:latest',
           '--port', '8080',
           '--memory', '1Gi',
           '--cpu', '1',
           '--max-instances', '10',
           '--min-instances', '0']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
