steps:
  # Build and deploy orchestrator service
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-orchestrator'
    args:
    - 'run'
    - 'deploy'
    - 'helios-orchestrator'
    - '--source'
    - './orchestrator'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--runtime'
    - 'python313'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '300s'
    - '--concurrency'
    - '80'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'ENV=production,PYTHONUNBUFFERED=true'

  # Build and deploy agents service
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-agents'
    args:
    - 'run'
    - 'deploy'
    - 'helios-ai-agents'
    - '--source'
    - './agents'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--runtime'
    - 'python313'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '5'
    - '--timeout'
    - '600s'
    - '--concurrency'
    - '50'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'ENV=production,PYTHONUNBUFFERED=true'

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  env:
    - 'CLOUDSDK_PYTHON=python3.13'
