steps:
  # Build and test the package first
  - name: 'python:3.12'
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        python -c "import helios; print('Package imports successfully')"
        python -c "
        import os
        os.environ['SERVICE_TYPE'] = 'orchestrator'
        from main import app
        print('Orchestrator app loaded successfully')
        "
        python -c "
        import os  
        os.environ['SERVICE_TYPE'] = 'ai_agents'
        from main import app
        print('AI Agents app loaded successfully')
        "

  # Deploy Helios AI Orchestrator service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'helios-orchestrator'
      - '--source'
      - '.'
      - '--region=us-central1'
      - '--service-account=helios-vertex-ai@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-secrets=PRINTIFY_API_TOKEN=printify-api-token:latest,PRINTIFY_SHOP_ID=printify-shop-id:latest,GOOGLE_API_KEY=google-api-key:latest'
      - '--set-env-vars=SERVICE_TYPE=orchestrator'
      - '--command=gunicorn'
      - '--args=--bind=:$$PORT,--workers=4,--worker-class=uvicorn.workers.UvicornWorker,main:app'

  # Deploy Helios AI Agents service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'helios-ai-agents'
      - '--source'
      - '.'
      - '--region=us-central1'
      - '--service-account=helios-vertex-ai@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-secrets=PRINTIFY_API_TOKEN=printify-api-token:latest,PRINTIFY_SHOP_ID=printify-shop-id:latest,GOOGLE_API_KEY=google-api-key:latest'
      - '--set-env-vars=SERVICE_TYPE=ai_agents'
      - '--command=gunicorn'
      - '--args=--bind=:$$PORT,--workers=4,--worker-class=uvicorn.workers.UvicornWorker,main:app'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
