steps:
  # Build and deploy orchestrator service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'helios-orchestrator'
    - '--source'
    - '.'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--memory'
    - '512Mi'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'SERVICE_TYPE=orchestrator'

  # Build and deploy agents service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'helios-ai-agents'
    - '--source'
    - '.'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--memory'
    - '1Gi'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'SERVICE_TYPE=ai_agents'

timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'

