steps:
  # Build CEO orchestrator service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deployment/docker/Dockerfile.ceo', '-t', 'gcr.io/$PROJECT_ID/helios-ceo:latest', '.']

  # Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helios-ceo:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'helios-ceo', '--image', 'gcr.io/$PROJECT_ID/helios-ceo:latest', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--service-account', 'helios-automation-sa@$PROJECT_ID.iam.gserviceaccount.com']

images:
  - 'gcr.io/$PROJECT_ID/helios-ceo:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '900s'
