# Development Configuration for Helios Autonomous Store
# This file contains development-specific settings

# Google Cloud Configuration
google_cloud:
  project_id: "helios-pod-system"  # Development project
  region: "us-central1"
  zone: "us-central1-a"
  
  # Service Account Configuration
  service_account:
    name: "helios-automation-sa"
    key_file: "~/.config/helios/helios-sa.json"  # Local development path
  
  # APIs to enable
  required_apis:
    - "aiplatform.googleapis.com"
    - "cloudfunctions.googleapis.com"
    - "cloudrun.googleapis.com"
    - "firestore.googleapis.com"
    - "cloudstorage.googleapis.com"
    - "sheets.googleapis.com"
    - "drive.googleapis.com"
    - "secretmanager.googleapis.com"
    - "cloudscheduler.googleapis.com"
    - "pubsub.googleapis.com"

# AI Platform Configuration
ai_platform:
  vertex_ai:
    project_id: "helios-pod-system"
    location: "us-central1"
    
    models:
      gemini_pro:
        model_name: "gemini-1.5-pro"
        max_tokens: 4096  # Reduced for development
        temperature: 0.8
      gemini_flash:
        model_name: "gemini-1.5-flash"
        max_tokens: 4096  # Reduced for development
        temperature: 0.9
      gemini_ultra:
        model_name: "gemini-1.0-ultra"
        max_tokens: 16384  # Reduced for development
        temperature: 0.6
    
    image_generation:
      model: "imagen-2"  # Use cheaper model for development
      resolution: "512x512"  # Lower resolution for development
      format: "PNG"
      quality: "medium"
      safety_filtering: true

# MCP Integration Configuration
mcp_integration:
  server_url: "http://localhost:8080"  # Local development
  auth_token: "${GOOGLE_MCP_AUTH_TOKEN}"
  
  tools:
    google_trends:
      enabled: true
      rate_limit: 50  # Reduced for development
    social_media_scanner:
      enabled: true
      platforms: ["reddit"]  # Limited platforms for development
      rate_limit: 100  # Reduced for development
    news_analyzer:
      enabled: true
      sources: ["google_news"]  # Limited sources for development
      rate_limit: 75  # Reduced for development

# External APIs Configuration
external_apis:
  printify:
    api_token: "${PRINTIFY_API_TOKEN}"
    shop_id: "${PRINTIFY_SHOP_ID}"
    base_url: "https://api.printify.com/v1"
    rate_limit: 1.0  # Slower for development
    retry_attempts: 2
  
  etsy:
    api_key: "${ETSY_API_KEY}"
    base_url: "https://openapi.etsy.com/v3"
    rate_limit: 2.0  # Slower for development
    retry_attempts: 2

# Google Workspace Integration
google_workspace:
  sheets:
    tracking_spreadsheet_id: "${GOOGLE_SHEETS_TRACKING_ID}"
    update_frequency: "batch"  # Batch updates for development
  
  drive:
    root_folder_id: "${GOOGLE_DRIVE_FOLDER_ID}"
    folder_structure:
      product_images: "Dev/Product Images/{YYYY-MM-DD}"
      generated_designs: "Dev/Generated Designs/{trend_name}"
      marketing_assets: "Dev/Marketing Assets/{product_type}"
      analytics_reports: "Dev/Analytics Reports/{month}"

# Performance Configuration
performance:
  execution_timeout: 600  # Longer timeout for development
  min_opportunity_score: 6.0  # Lower threshold for development
  min_audience_confidence: 6.0  # Lower threshold for development
  min_profit_margin: 0.25  # Lower margin for development
  
  caching:
    trend_data_ttl: 1800  # 30 minutes for development
    printify_catalog_ttl: 43200  # 12 hours for development
    api_responses_ttl: 600  # 10 minutes for development
  
  scaling:
    enable_auto_scaling: false  # Disabled for development
    min_instances: 0
    max_instances: 2
    target_cpu_utilization: 80

# Security Configuration
security:
  authentication:
    require_authentication: false  # Disabled for development
    allowed_origins: ["http://localhost:3000", "http://localhost:8080"]
  
  data_protection:
    encryption_at_rest: true
    encryption_in_transit: true
    pii_handling: "minimal"
  
  api_security:
    rate_limiting: false  # Disabled for development
    request_validation: true
    content_moderation: false  # Disabled for development

# Monitoring and Observability
monitoring:
  logging:
    level: "DEBUG"  # More verbose for development
    destination: "console"  # Console output for development
  
  metrics:
    collection_interval: 300  # 5 minutes for development
    custom_metrics: false  # Disabled for development
  
  alerting:
    enabled: false  # Disabled for development
    notification_channels: ["console"]
    critical_alerts: ["service_down"]

# Error Handling and Recovery
error_handling:
  retry_strategy:
    max_retries: 2  # Fewer retries for development
    exponential_backoff: true
    base_delay: 0.5  # Faster retries for development
  
  circuit_breaker:
    enabled: false  # Disabled for development
    failure_threshold: 3
    recovery_timeout: 30  # Faster recovery for development
  
  dead_letter_queue:
    enabled: false  # Disabled for development
    max_retries: 2

# Content Safety
content_safety:
  image_moderation:
    enabled: false  # Disabled for development
    safety_filters: ["adult", "violence"]
    confidence_threshold: 0.7
  
  text_moderation:
    enabled: false  # Disabled for development
    profanity_filter: false
    hate_speech_detection: false
    brand_safety_check: false

# Publication Settings
publication:
  dry_run: true  # Always dry run in development
  allow_live_publishing: false
  quality_gates:
    image_validation: false  # Disabled for development
    pricing_validation: true
    content_moderation: false  # Disabled for development
  
  batch_processing:
    enabled: false  # Disabled for development
    max_concurrent: 2
    batch_size: 5

# Development Tools
development:
  hot_reload: true
  debug_mode: true
  mock_external_apis: false  # Use real APIs for testing
  local_emulators:
    firestore: false
    pubsub: false
    storage: false
  
  testing:
    run_tests_on_startup: true
    coverage_reporting: true
    performance_testing: false
