# Production Configuration for Helios Autonomous Store
# This file contains production-specific settings

# Google Cloud Configuration
google_cloud:
  project_id: "helios-autonomous-store"
  region: "us-central1"
  zone: "us-central1-a"
  
  # Service Account Configuration
  service_account:
    name: "helios-automation-sa"
    key_file: "/secrets/helios-sa.json"
  
  # APIs to enable
  required_apis:
    - "aiplatform.googleapis.com"
    - "cloudfunctions.googleapis.com"
    - "cloudrun.googleapis.com"
    - "firestore.googleapis.com"
    - "cloudstorage.googleapis.com"
    - "sheets.googleapis.com"
    - "drive.googleapis.com"
    - "secretmanager.googleapis.com"
    - "cloudscheduler.googleapis.com"
    - "pubsub.googleapis.com"

# AI Platform Configuration
ai_platform:
  vertex_ai:
    project_id: "helios-autonomous-store"
    location: "us-central1"
    
    models:
      gemini_pro:
        model_name: "gemini-1.5-pro"
        max_tokens: 8192
        temperature: 0.7
      gemini_flash:
        model_name: "gemini-1.5-flash"
        max_tokens: 8192
        temperature: 0.8
      gemini_ultra:
        model_name: "gemini-1.0-ultra"
        max_tokens: 32768
        temperature: 0.5
    
    image_generation:
      model: "imagen-3"
      resolution: "1024x1024"
      format: "PNG"
      quality: "high"
      safety_filtering: true

# MCP Integration Configuration
mcp_integration:
  server_url: "https://mcp-server-helios-xxxxx-uc.a.run.app"
  auth_token: "${GOOGLE_MCP_AUTH_TOKEN}"
  
  tools:
    google_trends:
      enabled: true
      rate_limit: 100  # requests per hour
    social_media_scanner:
      enabled: true
      platforms: ["twitter", "reddit", "youtube"]
      rate_limit: 200  # requests per hour
    news_analyzer:
      enabled: true
      sources: ["google_news", "rss_feeds", "news_api"]
      rate_limit: 150  # requests per hour

# External APIs Configuration
external_apis:
  printify:
    api_token: "${PRINTIFY_API_TOKEN}"
    shop_id: "${PRINTIFY_SHOP_ID}"
    base_url: "https://api.printify.com/v1"
    rate_limit: 0.5  # seconds between requests
    retry_attempts: 3
  
  etsy:
    api_key: "${ETSY_API_KEY}"
    base_url: "https://openapi.etsy.com/v3"
    rate_limit: 1.0  # seconds between requests
    retry_attempts: 3

# Google Workspace Integration
google_workspace:
  sheets:
    tracking_spreadsheet_id: "${GOOGLE_SHEETS_TRACKING_ID}"
    update_frequency: "real_time"
  
  drive:
    root_folder_id: "${GOOGLE_DRIVE_FOLDER_ID}"
    folder_structure:
      product_images: "Product Images/{YYYY-MM-DD}"
      generated_designs: "Generated Designs/{trend_name}"
      marketing_assets: "Marketing Assets/{product_type}"
      analytics_reports: "Analytics Reports/{month}"

# Performance Configuration
performance:
  execution_timeout: 300  # seconds
  min_opportunity_score: 7.0
  min_audience_confidence: 7.0
  min_profit_margin: 0.35
  
  caching:
    trend_data_ttl: 3600  # 1 hour
    printify_catalog_ttl: 86400  # 24 hours
    api_responses_ttl: 300  # 5 minutes
  
  scaling:
    enable_auto_scaling: true
    min_instances: 1
    max_instances: 10
    target_cpu_utilization: 70

# Security Configuration
security:
  authentication:
    require_authentication: true
    allowed_origins: ["https://helios-autonomous-store.com"]
  
  data_protection:
    encryption_at_rest: true
    encryption_in_transit: true
    pii_handling: "minimal"
  
  api_security:
    rate_limiting: true
    request_validation: true
    content_moderation: true

# Monitoring and Observability
monitoring:
  logging:
    level: "INFO"
    destination: "cloud_logging"
  
  metrics:
    collection_interval: 60  # seconds
    custom_metrics: true
  
  alerting:
    enabled: true
    notification_channels: ["email", "pagerduty"]
    critical_alerts: ["service_down", "high_error_rate", "performance_degradation"]

# Error Handling and Recovery
error_handling:
  retry_strategy:
    max_retries: 3
    exponential_backoff: true
    base_delay: 1  # seconds
  
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 60  # seconds
  
  dead_letter_queue:
    enabled: true
    max_retries: 3

# Content Safety
content_safety:
  image_moderation:
    enabled: true
    safety_filters: ["adult", "violence", "hate"]
    confidence_threshold: 0.8
  
  text_moderation:
    enabled: true
    profanity_filter: true
    hate_speech_detection: true
    brand_safety_check: true

# Publication Settings
publication:
  dry_run: false
  allow_live_publishing: false
  quality_gates:
    image_validation: true
    pricing_validation: true
    content_moderation: true
  
  batch_processing:
    enabled: true
    max_concurrent: 5
    batch_size: 10
